### ISSUE TITLE
Button za shutdown

### ISSUE THREAD

**Issue by JanezCim** [JanezCim/cnc_rpi_web#1]
A bi lahko šeen button na Web-u naredu kjer gor piše shutdown, pa nardiš šeeno funkcijo v pythonu k ga button pokliče :D

**Comment by timkambic** [comment]
Evo dodano. Sem pa moral mergat iz terminala, tko da upam da nisem kj zbrisov :stuck_out_tongue_closed_eyes: :nauseated_face:

**Comment by JanezCim** [comment]
A bi lahko kako enostavno naredu da se gumb ob prvem pritisku spremeni barvo, po drugem pa se bo shutdownu. Probu sm to enostavno narest z zadnjim commitom, sam moram umes refreshat da se zelena barva dejansko vid...

**Comment by JanezCim** [comment]
Ta želja ni več relevantna. Zapiram :)
